donejs/generator-donejs

app/index.js

This is for #9. The package name is not needed to be part of the main
because the npm plugin adds this already itself.

Remove package name as part of the main

---

app/index.js

This adds two new modules to the npmIgnore list:
* generator-donejs
* yeoman-environment
Neither are used client-side so they are safe to ignore.
Closes #14

Adding generator deps to npmIgnore

---

app/templates/test.html

This fixes the main test.html page's steal script so that it looks in
the correct `node_modules/` folder, this is a regression caused by when
we moved it out of hte `src/` folder.

Fix test page's steal script

---

app/templates/build.js

Because of
https://github.com/stealjs/steal-bundler/commit/12889819182f10797e20b525c3eff9b1e7fc831c
The problem with bootstrap's css is now fixed. So re-enabling the
`bundleAssets` option.

Re-enable bundle assets

---

app/index.js
app/templates/src/models/fixtures/fixtures.js
supermodel/templates/fixtures/model.js

Because one can not simply move a repository and not update the things that use it.

Update generators to use can-fixture

---

app/index.js

When setting `skipInstall`, dependencies are not written to `package.json`. This PR makes sure that they are anyway.

Write dependencies instead when installation is skipped

---

package.json
supermodel/index.js
test/supermodel.test.js
test/tests/basics/package.json

This was added in lodash 4.0 and we are using 3.x. Because I don't want
to risk other breaking changes by including lodash 3.x, I'm just going
to depend on lodash.upperfirst and use it where needed. Closes #85

Add dependency on lodash.upperfirst

---

plugin/index.js

It got removed in https://github.com/donejs/generator-donejs/commit/7cb31333b655f473156881ba16dca55e781c8342#diff-77133e49354dd4b50f49c5d8634333ddL174 but we need it to host the static files.

Adding can-ssr dependency back to plugin generator

---

plugin/index.js

Currently, when generating a plugin with the plugin generator, DoneJS 8.0 is failing when you `donejs develop`, because it is lookign for a `can-serve` that no longer exists.

Update plugin-generator to use done-serve instead of can-serve

---

generator/index.js
generator/packages.js
lib/utils.js
test/util.test.js

This fixes #130 fixing the generator generator. Creates
`generator/packages.js` which lists the dependencies and version ranges
that will be installed.

Make generator installs be for version ranges

---

plugin/index.js

Any project that uses a plugin, like bit-tabs and tries to do an export
will break currently because cssify is listed as a devDependency which
it needs to actually ship with the plugin.

Move cssify into a regular dependency

---

app/templates/src/index.stache

This simplifies the production script tag so that it uses the new
preconfigured steal.production.js that was added in Steal 1.0.
Closes #173

Use a simplified production steal script tag

---

app/index.js

This fixes the default renderingBaseURL so that it works with nested
routes.
Closes #177

Update the default renderingBaseURL

---

app/index.js
app/templates/src/index.md
component/index.js
component/templates/modlet/component.md
module/index.js
module/templates/module.md
plugin/index.js
plugin/templates/plugin.md

Even though documentjs is not installed by default, we're still going to
write out .md files so if you decide to add documentjs later you won't
have to go back and add docs for everything you've generated.

changing generators to write out .md files again

---

app/index.js

This adds in additional package.json defaults so that there is always a
description and license for the application. This prevents warnings when
doing fresh `npm install`s.
Closes #199

Additional package.json defaults

---

supermodel/templates/model.js
test/plugin.test.js

This uses the more modern DefineMap/List syntax of `any` to denote a
property that can be any type and `#` for the list's Map type.
Closes #214

Use modern DefineMap/List syntax

---

app/index.js
test/app.test.js

kebabCasing a package name can destroy what are otherwise valid package names. The fix is to first check if the name is valid, and if so to leave it alone. Changing only happens if the name is invalid.
Closes #225

Only kebabCase invalid npm names

---

plugin/templates/README.md
plugin/templates/index.html

- The `pre` sections now scroll horizontally
- Use SVG instead of PNG for the Travis icon (and right-align it)
- Default to a greater width
Before:
After:

Improve the generated plugin index.html

---

plugin/templates/static/.jshintrc

This change makes the plugin generator consistent with the [generator generator](https://github.com/donejs/generator-donejs/blob/801dace37f583f967ca68d1e3109c169ffec3bd2/generator/templates/static/.jshintrc#L10).
JSHint will no longer complain about the function being “used before it was defined” in this example:
```js
work();
function work() {}
```

Set "latedef" to "nofunc" in the plugin generator

---

supermodel/templates/model.js

Moves the creation of the algebra until after the List, since logically
the algebra informs how lists are handled. Closes #271

Make algebra after the List in supermodel template

---

app/templates/src/app.js

This prevents the warning that occurs with all donejs apps due to us
using this in the index.stache file.

Provide env.NODE_ENV as a default AppViewModel property

---

app/templates/src/app.js
app/templates/src/index.stache
package.json
test/app.test.js
test/app_tests/routing.test.js

This updates the app generator so that the routing works using
the built-in `route.data` rather than setting it.

Update generated app.js for DoneJS 3 routing

---

app/templates/src/app.js

This uses can-route-pushstate so that we can correctly alias it in
development.html.
Fixes #289

Use the can-route-pushstate package

---

app/templates/src/app.js
component/templates/modlet/component.js
test/component.test.js

This makes it so that both the ViewModel and Component get exported from
modlets. The Component gets exported both as a constructor-case name
like `PmoRestaurantList` and as the default export. The ViewModel is
exported as `ViewModel`.

Export the ViewModel and Component from modlets

---

supermodel/templates/model.js
test/supermodel.test.js

This adds a name for model types like:
```js
const Restaurant = DefineMap.extend("Restaurant", {
...
});
```
Closes #299

Give model types a function name

---

app/index.js
test/app.test.js

This switches to using the `can` plugin for steal. This prevents the
need for directly depending on steal-stache within donejs projects,
which should eliminate multiple version warnings from occuring when
upgrading canjs versions.

Use `can` plugin for steal

---

plugin/index.js
plugin/templates/test.html
plugin/templates/test.js
test/plugin.test.js

This will keep the name in the package.json if you provide a name like "@bitovi/my-plugin" and will prompt if you are wish the package to be public which is default and will add "--access public" to the npm publish scripts.
Ref - https://github.com/donejs/donejs/issues/1176

Handle scoped name of projects

---

component/index.js
test/component.test.js

Fix trailing slash on component name
