donejs/generator-donejs

app/templates/index.stache

Template imports use the full module name

---

app/templates/index.stache

Development <script> should have forward /

---

app/templates/build.js
app/templates/src/app.js

Adding build.js (#39) and importing can/route/pushtate (#38)

---

app/index.js
app/templates/development.html
app/templates/production.html
app/templates/src/index.stache
app/templates/src/test/functional.js

This should finalize the quick start guide.

Updating to latest DoneJS application structure and features

---

app/templates/production.html

Fix script placement

---

.travis.yml
app/index.js
app/templates/src/models/fixtures/fixtures.js
app/templates/src/test/test.js

Some small tweaks for the app generator. See related issues.

Minor tweaks

---

app/index.js

Part of https://github.com/donejs/donejs/issues/455

Use loglevel error when npm installing

---

app/index.js
package.json
test/app.test.js

For https://github.com/donejs/donejs/issues/476

Write specific versions into package.json and run npm install separately

---

component/index.js

add the posibility to set a configMain file, preferably the package.json.
the attributes from the .yo-rs.json are prefered.
throw also an error if no folder or appName is specified. #60 
i do not add the package.json to the app init (https://github.com/donejs/generator-donejs/blob/master/app/index.js#L106-L107). i could if requested...

reading config attributes from package.json if specified in the .yo-rs.json

---

app/templates/_gitignore

For https://github.com/donejs/donejs/issues/492

Add other DoneJS build artifact folders to .gitignore

---

app/index.js
component/index.js

package.json is now the main config file.
appName and sourceFolder will get from package.json

#60 use package json

---

app/index.js
component/index.js
package.json
supermodel/index.js

`this.fs.accessSync` is not a valid function, yeoman does't support all the functions from fs and fs-extra
@daffl @matthewp can you looked into it and merge?
after that the CI on donejs-cli should pass

read "appName" and "folder" from package.json

---

supermodel/index.js

Use camelCased model class names

---

app/templates/readme.md
plugin/templates/readme.md

This pull request adds more details to the readme of a newly created DoneJS app or plugin.

Adding more details to the readme

---

plugin/index.js
test/plugin.test.js

Fix package.json main

---

plugin/index.js

Add live-reload dependency and develop command

---

plugin/index.js
plugin/templates/plugin_test.js
plugin/templates/test/test.js
test/plugin.test.js

Move plugin test so that it is not necessary to change

---

app/index.js
component/templates/component.component
package.json

Closes https://github.com/donejs/donejs/issues/467

Some generator tweaks for DoneJS 0.7.0

---

readme.md

It only really works through the DoneJS cli.
Closes #75, closes #89

Update readme on how to use the generator correctly

---

app/index.js
package.json

Closes https://github.com/donejs/donejs/issues/543 and closes https://github.com/donejs/generator-donejs/issues/49

Fix name property and throw error for invalid module names

---

generator/index.js
generator/templates/default/index.js
generator/templates/readme.md
generator/templates/static/.travis.yml
generator/templates/static/lib/index.js

Cleans up some mistakes so that everything runs smoothly.

Some more tweaks for the the generator generator

---

plugin/templates/plugin_test.js
plugin/templates/test/test.js

Fix paths in plugin test files

---

app/index.js
app/templates/src/app.js
app/templates/src/index.stache

This will support the new done-ssr and done-serve modules.

Update for donejs 0.8.0

---

supermodel/index.js
test/generator.test.js
test/supermodel.test.js

This adds a test and fix for #104.

Trim supermodel URL

---

.travis.yml
package.json

This adds code coverage, closing #105

Adds code coverage with Istanbul

---

app/index.js
component/index.js
lib/utils.js
package.json
plugin/index.js
readme.md
supermodel/index.js
test/app.test.js
test/component.test.js
test/helpers.js
test/supermodel.test.js
test/tests/basics/package.json
test/tests/existing/package.json
test/tests/existing/src/models/fixtures/fixtures.js
test/tests/existing/src/models/test.js
test/tests/existing2/package.json
test/tests/existing2/src/models/fixtures/fixtures.js
test/tests/existing2/src/models/test.js
test/util.test.js

This gets us to 92%, but still only 76% on branches. Looking into what I can do.

Increase code coverage

---

generator/index.js
generator/templates/readme.md

Updating the readme for the generator guide

---

lib/utils.js
test/util.test.js

Closes https://github.com/donejs/generator-donejs/issues/120.

when adding imports, don't prepend a newline when last line is empty

---

app/templates/readme.md

Fix backticks in app template README

---

package.json
supermodel/index.js
test/supermodel.test.js

this implements https://github.com/donejs/donejs/issues/509

Fix 509 generate plural fixture names

---

.travis.yml
app/index.js
appveyor.yml
generator/packages.js
package.json
test/app.test.js

353 absolute path fix

---

app/index.js

This should fix it: https://github.com/donejs/donejs/issues/716

Use babel as the transpiler

---

app/templates/src/app.js
app/templates/src/index.stache
component/templates/component.component
component/templates/modlet/component.html
component/templates/modlet/component.js
component/templates/modlet/component_test.js
package.json
supermodel/templates/model.js
supermodel/templates/model_test.js

**NOTE** not ready to be merged yet.

Update generators to work with can3

---

app/index.js
test/app.test.js

Closes https://github.com/donejs/generator-donejs/issues/164.

adding steal-stache to the plugins config in the app generator

---

component/templates/component.component

closes https://github.com/donejs/generator-donejs/issues/167.

using view instead of template in .component generator

---

.travis.yml
app/index.js
test/app.test.js

Add done-css as a plugin.

---

app/templates/development.html
component/index.js
lib/utils.js
module/index.js
package.json
supermodel/index.js
test/app.test.js
test/app_tests/routing.test.js
test/utils.test.js

Closes https://github.com/donejs/generator-donejs/issues/113 and https://github.com/donejs/generator-donejs/issues/126.

Generator updates

---

module/index.js
test/module.test.js

https://github.com/donejs/generator-donejs/issues/179 broke the module generator, this fixes it and adds tests.

fixing module generator and adding a test

---

generator/packages.js
generator/templates/default/index.js

Re-closes https://github.com/donejs/generator-donejs/issues/179.

updating generated generator to use yeoman 1.0

---

component/index.js
module/index.js
supermodel/index.js
test/component.test.js
test/module.test.js
test/supermodel.test.js

closes https://github.com/donejs/generator-donejs/issues/189.

correctly handling arguments and adding tests

---

module/index.js
test/component.test.js
test/module.test.js
test/tests/existing/src/test/test.js

Closes https://github.com/donejs/generator-donejs/issues/127.

Module test

---

plugin/index.js
plugin/templates/index.html

Not the prettiest, but gets the job done:
closes https://github.com/donejs/generator-donejs/issues/102.

adding index.html page to plugin generator

---

component/index.js
lib/utils.js
package.json
test/utils.test.js

closes https://github.com/donejs/generator-donejs/issues/143.

validating component tag name

---

supermodel/templates/fixtures/model.js
supermodel/templates/model.js

Closes https://github.com/donejs/generator-donejs/issues/193.
Also fixes part of https://github.com/donejs/donejs/issues/633 (guide still needs to be updated).

updating supermodel generator to use a default set algebra

---

app/index.js
component/index.js
generator/index.js
lib/baseGenerator.js
module/index.js
package.json
plugin/index.js
supermodel/index.js
test/app.test.js

closes https://github.com/donejs/donejs/issues/596.

Prevent errors when user does not have write permissions to their home directory

---

appveyor.yml
plugin/index.js

Related to https://github.com/donejs/generator-donejs/pull/212.

correcting version commit message

---

plugin/index.js
test/plugin.test.js

closes https://github.com/donejs/generator-donejs/issues/223.

updating dependencies installed by plugin generator

---

readme.md

Update documentation of new project APIs

---

app/templates/_gitignore

Alphabetize the directories in generated apps’ .gitignore

---

generator/packages.js

Order dependencies in generator/packages.js

---

readme.md

Part of https://github.com/donejs/donejs/issues/519

Document donejs add generators

---

plugin/templates/README.md

Remove AMD info from plugin generator readme

---

plugin/templates/CONTRIBUTING.md

Closes #254 ; that branch got muddled with trying to fix the build.

Add note on build minification

---

app/templates/test.html
component/templates/modlet/test.html
module/templates/test.html
plugin/templates/test.html

add doctype to test files

---

component/index.js
package.json
test/app.test.js
test/component.test.js
test/generator.test.js
test/module.test.js
test/plugin.test.js
test/supermodel.test.js
test/utils.test.js

It replaces ```assert``` for testing with ```yeoman-assert```

yeoman-assert as assertion library

---

component/index.js
test/component.test.js

Ignore trailing slashes when running donejs add component

---

component/index.js
test/component.test.js

Ignore trailing slashes on component name

---

.gitignore
app/templates/src/index.stache
supermodel/templates/model.js

Update templates to be compat with canjs 4

---

.travis.yml
app/templates/src/app.js
appveyor.yml
component/templates/component.component
component/templates/modlet/component.js
package.json
test/app.test.js

Use `default` instead of `value` for initial default values

---

.npmrc
app/templates/src/index.stache
component/index.js
package.json
supermodel/index.js
test/tests/existing2/src/models/fixtures/fixtures.js
test/tests/existing2/src/models/test.js

This is part of https://github.com/donejs/donejs/issues/1065

Use ~ instead of app name in imports

---

app/index.js
app/templates/src/app.js
app/templates/src/is-dev.js
package.json
test/app.test.js

Conditionally load can-debug in development

---

.gitignore
.npmrc
.travis.yml
app/index.js
app/templates/src/app.js
app/templates/src/index.stache
app/templates/src/is-dev.js
appveyor.yml
component/index.js
component/templates/component.component
component/templates/modlet/component.js
package.json
supermodel/index.js
supermodel/templates/model.js
test/app.test.js
test/tests/existing2/src/models/fixtures/fixtures.js
test/tests/existing2/src/models/test.js

Merge major into master

---

app/index.js
package.json
test/app.test.js

Closes https://github.com/donejs/donejs/issues/819

Use prompt defaults when option is passed in

---

app/templates/build.js
app/templates/development.html
app/templates/src/app.js
component/templates/component.component
component/templates/modlet/component.html
component/templates/modlet/component.js
supermodel/templates/model.js

Upgrade templates to support donejs 3

---

component/index.js
component/templates/component.component
component/templates/modlet/component.js
lib/utils.js
test/component.test.js

This adds ViewModel groupings to both the .component and the modlet
components.
For .component this also adds a name to the ViewModel for better
debuggability. Closes #287

Adds ViewModel groupings

---

app/index.js

Allow .component files in nested folders to be pages

---

supermodel/templates/fixtures/model.js

Update fixture templates

---

component/index.js
component/templates/modlet/component.html

Part of https://github.com/donejs/donejs/issues/1146

Update demo pages to use can-component constructors

---

component/index.js
test/component.test.js

This allows to generate components with same name as the app name.
https://github.com/donejs/donejs/issues/1175

Component with same name as app

---

plugin/templates/static/.travis.yml

For https://github.com/donejs/donejs/issues/1196

Update travis template to xenial
